### ISSUE TITLE
Palette problem

### ISSUE THREAD

**Issue by TachibanaYoshino** [CQFIO/PhotographicImageSynthesis#17]
In document GTA_Diversity_256p.py , you use the get_semantic_map function to get the semantic map, but the color palette of cityscapes is used in the get_semantic_map function. does this mean that the color palette of GTA5 and cityscapes are the same?

**Comment by CQFIO** [comment]
Yes, they are the same. You can download the GTA5 data from https://download.visinf.tu-darmstadt.de/data/from_games/

**Comment by TachibanaYoshino** [comment]
thanks a lot
