### ISSUE TITLE
GTA5 dataset image size

### ISSUE THREAD

**Issue by YellowPig-zp** [CQFIO/PhotographicImageSynthesis#23]
Hi Dr. Chen. It looks like you are using GTA5 dataset. It seems that the size of the image (512x256) is not at the same scale as that of the original GTA5 dataset(1914x1052). What preprocessing did you do? Did you scale and crop the image or simply just scale them?

**Comment by CQFIO** [comment]
I have tried both. The visual quality is similar. I think I cropped the input semantic images and rescaled the images by nearest neighbors in the provided model.
